databases:
  - name: engineer-db
    databaseName: engineer
    user: engineer
    plan: free # or starter, standard, etc.

services:
  - type: web
    name: engineer-web
    env: node
    plan: free # or starter, standard, etc.
    buildCommand: npm install && npm run build
    startCommand: npx prisma db push --accept-data-loss && npx prisma db seed && npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: engineer-db
          property: connectionString
      - key: NODE_ENV
        value: production
